name: Build & Test Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
    NETCORE_VERSION: |
      6.0.x
      7.0.x
    DOTNET_NOLOGO: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    NUGET_FEED: https://api.nuget.org/v3/index.json
    NUGET_KEY: ${{ secrets.NUGET_KEY }}

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Restore
      run: dotnet restore

    - name: Run Tests
      run: dotnet test -c Release --no-restore

  deploy:
    name: Publish NuGet Packages
    needs: build
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}

      - name: Pack Phetch.Core
        run: dotnet pack -v normal -c Release -o nupkg src/Phetch.Core/

      - name: Pack Phetch.Blazor
        run: dotnet pack -v normal -c Release -o nupkg src/Phetch.Blazor/

      - name: Push to NuGet Feed
        run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --api-key $NUGET_KEY --skip-duplicate
